### ISSUE TITLE
Is DTC?

### ISSUE THREAD

**Issue by baldoOsu** [StandardV/ValorantStreamsnipe#1]
Plis tell me this benevolent application is not dtc by vanguard-sama. I really do not want to get yeeted into the abyss for stream sniping my favorite streamer, APE SuperNova (https://www.twitch.tv/sup3rn0vaa)

**Comment by StandardV** [comment]
At this point in time it is just a 5 minutes script and since what it does is only taking screenshot and double check with twitch to see if the account is streaming or not, there'd be 0% percent that vanguard's gonna block you. Beside, what you done is only taking screenshot anyway so if there is 0.00001% of that accidentally happen, you can always argue with riot support but I doubt it will

**Comment by StandardV** [comment]
it could certainly search for those name like supernova though but I haven't make name variation feature for it just yet. Right now, if it meet an account like APE SuperNova, it will search for apesupernova and that's it. Further variation might be include later.

**Comment by baldoOsu** [comment]
oh damn thats crazy i dont think even gamerdoc can detect that

**Comment by StandardV** [comment]
I'll play a few valorant matches right now and make an example document. Hang on there!

**Comment by StandardV** [comment]
Updated! I'll close this ticket now since your issue is resolved. Feel free to open another one if there's any other problem
